SELECT * FROM PRODUTOS;

SELECT NOMEDOPRODUTO, PRECOUNITARIO FROM PRODUTOS;

SELECT NOMEDOPRODUTO, PRECOUNITARIO, PRECOUNITARIO FROM PRODUTOS;

SELECT NOMEDOPRODUTO, PRECOUNITARIO, PRECOUNITARIO * 1.2 FROM PRODUTOS;

SELECT NOMEDOPRODUTO AS PRODUTO, PRECOUNITARIO AS PREÇO, PRECOUNITARIO * 1.2 AS "PREÇO PLAYBOY" FROM PRODUTOS;

SELECT NOMEDOPRODUTO PRODUTO, PRECOUNITARIO PREÇO, PRECOUNITARIO * 1.2 "PREÇO PLAYBOY" FROM PRODUTOS;

SELECT NOME, SOBRENOME FROM EMPREGADOS;

SELECT NOME ||' '|| SOBRENOME FROM EMPREGADOS;

SELECT NOMEDOPRODUTO, PRECOUNITARIO FROM PRODUTOS WHERE PRECOUNITARIO <= 60 AND PRECOUNITARIO >= 40;

SELECT NOMEDOPRODUTO, PRECOUNITARIO FROM PRODUTOS WHERE PRECOUNITARIO NOT BETWEEN 40 AND 60;

SELECT * FROM EMPREGADOS WHERE REGIAO IS NULL;

SELECT * FROM EMPREGADOS WHERE REGIAO IS NOT NULL;

SELECT NOMEDOPRODUTO, TO_CHAR(PRECOUNITARIO, 'L00.00') FROM PRODUTOS;

SELECT NOMEDOPRODUTO, DECODE(LENGTH(PRECOUNITARIO), 5, TO_CHAR(PRECOUNITARIO, 'L99.99'), TO_CHAR(PRECOUNITARIO, 'L999.99')) FROM PRODUTOS;

SELECT NOMEDOPRODUTO, TO_CHAR(PRECOUNITARIO, 'L99.99') FROM PRODUTOS;

select cargo, count(*) from empregados group by cargo;